# Generated by Django 6.0.4 on 2026-04-27 18:59

import uuid
from django.db import migrations, models


def populate_usuario_uuid(apps, schema_editor):
    Usuario = apps.get_model('Campus360_app', 'Usuario')
    for usuario in Usuario.objects.filter(id__isnull=True):
        usuario.id = uuid.uuid4()
        usuario.save(update_fields=['id'])


class Migration(migrations.Migration):

    dependencies = [
        ('Campus360_app', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(null=True, db_index=True, editable=False),
        ),
        migrations.RunPython(populate_usuario_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
